---
title: "Triad Networks"
author: "Tim Vigers"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/Users/timvigers/Documents/GitHub/MS-Thesis")
library(knitr)
library(cit)
library(bnlearn)
library(rjags)
library(MCMCvis)
library(tidyverse)
set.seed(1017)
```

```{r data import,echo=FALSE}
# Load list and data
load("./data/networks/pair_list.Rdata")
load("./data/networks/pair_data.Rdata")
pair_data$T1Dgroup = factor(pair_data$T1Dgroup)
```

```{r model structures,echo=FALSE}
# Define all network structures
# 3 arcs
struct1 = "[T1Dgroup][methyl|T1Dgroup:metab][metab|T1Dgroup]"
struct2 = "[T1Dgroup][methyl|T1Dgroup][metab|T1Dgroup:methyl]"
struct3 = "[T1Dgroup|methyl:metab][methyl][metab|methyl]"
struct4 = "[T1Dgroup|methyl][methyl][metab|methyl:T1Dgroup]"
struct5 = "[T1Dgroup|metab:methyl][methyl|metab][metab]"
struct6 = "[T1Dgroup|metab][methyl|metab:T1Dgroup][metab]"
# 2 arcs
struct7 = "[T1Dgroup][methyl|T1Dgroup][metab|T1Dgroup]"
struct8 = "[T1Dgroup|methyl][methyl][metab|T1Dgroup]"
struct9 = "[T1Dgroup|metab][methyl|T1Dgroup][metab]"
struct10 = "[T1Dgroup|metab:methyl][methyl][metab]"
struct11 = "[T1Dgroup|methyl][methyl][metab|methyl]"
struct12 = "[T1Dgroup][methyl|T1Dgroup][metab|methyl]"
struct13 = "[T1Dgroup|methyl][methyl|metab][metab]"
struct14 = "[T1Dgroup][methyl|metab:T1Dgroup][metab]"
struct15 = "[T1Dgroup|metab][methyl|metab][metab]"
struct16 = "[T1Dgroup][methyl|metab][metab|T1Dgroup]"
struct17 = "[T1Dgroup|metab][methyl][metab|methyl]"
struct18 = "[T1Dgroup][methyl][metab|methyl:T1Dgroup]"
# 1 arc
struct19 = "[T1Dgroup][methyl|T1Dgroup][metab]"
struct20 = "[T1Dgroup][methyl][metab|T1Dgroup]"
struct21 = "[T1Dgroup|methyl][methyl][metab]"
struct22 = "[T1Dgroup][methyl][metab|methyl]"
struct23 = "[T1Dgroup|metab][methyl][metab]"
struct24 = "[T1Dgroup][methyl|metab][metab]"
# Print all
# invisible(lapply(paste0("struct",1:24), function(x){
#   mod = get(x)
#   plot(model2network(mod),main = x)
#   }))
```

# CIT Package

```{r cit on all,echo=FALSE,eval=FALSE}
cits = apply(pairs, 1, function(x){
  methyl = as.character(x["methyl"])
  metab = as.character(x["metab"])
  temp = pair_data[,c("T1Dgroup",methyl,metab)]
  temp = temp[complete.cases(temp),]
  y = as.numeric(temp$T1Dgroup) - 1
  X = temp[,c(methyl,metab)]
  cinf1 = cit.bp(L = X[,1],G = X[,2],T = y)
  cinf2 = cit.bp(L = X[,2],G = X[,1],T = y)
  p = min(cinf1$p_cit,cinf2$p_cit)
  d = which.min(c(cinf1$p_cit,cinf2$p_cit))
  d = ifelse(d == 1,">","<")
  if (p < 0.05) {return(paste(methyl,d,metab,p))} else {NA}
})
# Convert to dataframe
cits = as.data.frame(cits[!is.na(cits)])
cits = separate(cits,"cits[!is.na(cits)]",c("methyl","direction","metab","cit p"),
                sep = " ")
cits$`cit p` = round(as.numeric(cits$`cit p`),3)
cits = cits[order(cits$`cit p`),]
rownames(cits) = 1:nrow(cits)
# Write
save(cits,file = "./data/networks/cits.Rdata")
```

```{r load cits,echo=FALSE}
load("./data/networks/cits.Rdata")
```

Using a threshold of p < 0.05 for the omnibus CIT test, there are `r nrow(unique(cits))` unique pairs with significant mediation. Within these pairs, there are `r length(unique(cits$methyl))` unique probes and `r length(unique(cits$metab))` unique metabolites.

# MCMC

```{r mcmc test,echo=FALSE,eval=FALSE}
# MCMC parameters
n_adapt = 1000
iter = 10000
vars = c("alpha0","alpha","beta0","beta","gamma0","gamma")
# All pairs from cit package
# DIC for each model
all_dics = apply(cits,1,function(x){
  methyl = x["methyl"]
  metab = x["metab"]
  temp = pair_data[,c("T1Dgroup",methyl,metab)]
  temp = temp[complete.cases(temp),]
  temp$T1Dgroup = ifelse(temp$T1Dgroup == "T1D control",0,1)
  # data for jags
  N = nrow(temp)
  jags_data = list(t1d=c(temp[,"T1Dgroup"]),methyl=c(temp[,methyl]),
                   metab=c(temp[,metab]),
                   N=N)
  # Test all structures
  dics = lapply(paste0("struct",1:24), function(x){
    mod = jags.model(paste0("./code/jags/",x,".jags"),quiet=T,
                     data = jags_data, n.adapt = n_adapt,n.chains = 2)
    dic = dic.samples(mod,n.iter = iter,progress.bar="none")
    return(round(sum(dic$deviance) + sum(dic$penalty),1))
  })
  return(dics)
})
save(all_dics,file = "./data/networks/all_dic.Rdata")
# Samples for all models
all_samples = apply(cits,1,function(x){
  methyl = as.character(x["methyl"])
  metab = as.character(x["metab"])
  temp = pair_data[,c("T1Dgroup",methyl,metab)]
  temp = temp[complete.cases(temp),]
  temp$T1Dgroup = ifelse(temp$T1Dgroup == "T1D control",0,1)
  # data for jags
  N = nrow(temp)
  jags_data = list(t1d=c(temp[,"T1Dgroup"]),methyl=c(temp[,methyl]),
                   metab=c(temp[,metab]),
                   N=N)
  # Test all structures
  samples = lapply(paste0("struct",1:24), function(x){
    mod = jags.model(paste0("./code/jags/",x,".jags"),quiet=T,
                     data = jags_data, n.adapt = n_adapt,n.chains = 2)
    coda = coda.samples(mod,variable.names = vars,n.iter = iter,progress.bar="none")
    return(coda)
  })
  return(samples)
})
save(all_samples,file = "./data/networks/all_samples.Rdata")
```

```{r load dics,echo=FALSE}
load("./data/networks/all_dic.Rdata")
load("./data/networks/all_samples.Rdata")
```

## Structure table

```{r mcmc tabs,echo=FALSE}
Structure = unlist(lapply(all_dics, which.min))
tabs = table(Structure)
kable(tabs)
invisible(lapply(names(tabs), function(x){
  mod = get(paste0("struct",x))
  plot(model2network(mod),main = paste("Structure",x))
}))
kable(cits[which(Structure == 10),],row.names = F)
```