# Define all network structures
# 3 arcs
struct1 = "[T1Dgroup][methyl|T1Dgroup:metab][metab|T1Dgroup]"
struct2 = "[T1Dgroup][methyl|T1Dgroup][metab|T1Dgroup:methyl]"
struct3 = "[T1Dgroup|methyl:metab][methyl][metab|methyl]"
struct4 = "[T1Dgroup|methyl][methyl][metab|methyl:T1Dgroup]"
struct5 = "[T1Dgroup|metab:methyl][methyl|metab][metab]"
struct6 = "[T1Dgroup|metab][methyl|metab:T1Dgroup][metab]"
# 2 arcs
struct7 = "[T1Dgroup][methyl|T1Dgroup][metab|T1Dgroup]"
struct8 = "[T1Dgroup|methyl][methyl][metab|T1Dgroup]"
struct9 = "[T1Dgroup|metab][methyl|T1Dgroup][metab]"
struct10 = "[T1Dgroup|metab:methyl][methyl][metab]"
struct11 = "[T1Dgroup|methyl][methyl][metab|methyl]"
struct12 = "[T1Dgroup][methyl|T1Dgroup][metab|methyl]"
struct13 = "[T1Dgroup|methyl][methyl|metab][metab]"
struct14 = "[T1Dgroup][methyl|metab:T1Dgroup][metab]"
struct15 = "[T1Dgroup|metab][methyl|metab][metab]"
struct16 = "[T1Dgroup][methyl|metab][metab|T1Dgroup]"
struct17 = "[T1Dgroup|metab][methyl][metab|methyl]"
struct18 = "[T1Dgroup][methyl][metab|methyl:T1Dgroup]"
# 1 arc
struct19 = "[T1Dgroup][methyl|T1Dgroup][metab]"
struct20 = "[T1Dgroup][methyl][metab|T1Dgroup]"
struct21 = "[T1Dgroup|methyl][methyl][metab]"
struct22 = "[T1Dgroup][methyl][metab|methyl]"
struct23 = "[T1Dgroup|metab][methyl][metab]"
struct24 = "[T1Dgroup][methyl|metab][metab]"
# All
all_structs = lapply(paste0("struct",1:24),get)