---
title: "A Mediation Approach to Discovering Causal Relationships Between the Metabolome and DNA Methylation in Type 1 Diabetes"
date: ""
author:
- Timothy Vigers, B.A.^[UCD], Lauren A. Vanderlinden, M.S., Randi K. Johnson, Ph.D., Patrick M. Carry, M.S., Alexander M. Kaizer, Ph.D., Jill M. Norris, Ph.D., Katerina Kechris, Ph.D.
bibliography: "/Users/timvigers/Dropbox/Miscellaneous/references.bib"
csl: "/Users/timvigers/Dropbox/Miscellaneous/american-medical-association.csl"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Abstract

## Objective:

## Methods:

## Results:

## Conclusion:

\newpage

# Introduction

\newpage

# Methods

## Study Design and Participants

The Diabetes Autoimmunity Study in the Young (DAISY) cohort follows 2547 high-risk children in Colorado for the development of IA and T1D. Study participants were recruited via newborn screening at St. Joseph's Hospital in Denver, CO, USA and from unaffected first-degree relatives (FDR) of type 1 diabetes patients. The study follows participants prospectively and includes blood sample collection at 9, 15, and 24 months, then annual collection until islet autoimmunity (IA) is detected. IA is defined as the second consecutive visit at which a confirmed auto-antibody to insulin, GAD65, IA-2, or ZnT8 was detected.2 Participants who develop IA are asked to follow an accelerated protocol with visits and blood sample collection every 3-6 months, until they are diagnosed with diabetes by a physician. T1D cases were matched to controls by age at SV, race/ethnicity, and sample availability. The majority of participants were Non-Hispanic White (NHW), and race/ethnicity was categorized into NHW and Other for matching and analysis. All DAISY protocols were approved by the Colorado Multiple Institutional Review Board (COMIRB 92-080), and informed consent was obtained from all participants. All research was performed in accordance with relevant guidelines and regulations.[@johnsonLongitudinalDNAMethylation2020]

Participants with both methylation and metabolomic measures at the visit at which seroconversion was detected (SV) and the visit immediately prior (pre-seroconversion or PSV) were selected for these analyses. 

## DNA Methylation

T1D cases and matched controls were randomly assigned to either the 450 K group (which included duplicate samples for quality control) or EPIC group (which included replicates from the 450 K set for quality control). DNA methylation was profiled in peripheral whole blood using the Infinium HumanMethylation450K Beadchip (Illumina, San Diego, CA, USA, “450 K”) for the 450 K set, and the Infinium HumanMethylation EPIC Beadchip (“EPIC”) was used for the EPIC set. Both sets underwent identical pre-processing using the SeSAMe pipeline[@zhouSeSAMeReducingArtifactual2018], and measurement platform was included as a covariate in all statistical models in order to account for technological batch effects.

The SeSAMe pipeline was implemented using the sesame package (v1.0.0) in R (v3.5.2), and consists of Noob normalization[@tricheLowlevelProcessingIllumina2013] , non-linear dye bias correction, and pOOBAH to help identify failed hybridization. Next, arrays with high proportion of failed probes (100,000 failed probes for 450 K and 200,000 failed probes for EPIC) were removed (450 K = 6, EPIC = 2), along with arrays with discordant predicted sex and clinically recorded sex (450 K = 5, EPIC = 2) Probes missing in at least 1 sample were also removed from subsequent analyses (450 K = 109,956, EPIC = 202,222). ComBat[@leekSvaPackageRemoving2012] was used to remove batch effects using plate and row to delineate batch.

## Metabolomics

Untargeted metabolomics were obtained using gas chromatography-time of flight mass spectrometry (GC-TOF MS), charged surface hybrid column quadrupole time of flight mass spectrometry (CSH-QTOF MS), and hydrophilic interaction chromatography quadrupole time of flight mass spectrometry (HILIC-QTOF MS), at the NIH West Coast Metabolomics Center at the University of California, Davis. Non-fasting plasma samples were prepared and analyzed as previously described in Johnson et al. [@johnsonMetabolomicsrelatedNutrientPatterns2020]

For GC-TOF data, peak picking and annotation was performed using BinBase.[@skogersonVolatileCompoundBinBase2011] CSH-QTOF MS and HILIC-QTOF MS were processed using MS-Dial[@tsugawaMSDIALDataindependentMS2015] and complex lipids were annotated with LipidBlast[@kindLipidBlastSilicoTandem2013] and Massbank of North America (http://mona.fiehnlab.ucdavis.edu/), and erroneous peaks were removed using MSFLO.[@defeliceMassSpectralFeature2017]

After collection, annotation, and postprocessing, metabolomics data were normalized using SERRF[@fanSystematicErrorRemoval2019],a QC-based method designed to account for batch effects. Samples with low abundance (n = 2) and metabolites with a coefficient of variation more than two absolute deviations from the median (n = 344) were excluded, and data were transformed using the box-cox method.[@boxAnalysisTransformations1964] After processing and quality checks, 2457 untargeted metabolites (including 1905 annotated) remained.[@johnsonMetabolomicsrelatedNutrientPatterns2020]

## Statistical Analysis

All analyses were performed using the R programming environment[@rcoreteamLanguageEnvironmentStatistical2021] and included only participants with methylation and metabolomics data at both their SV and PSV study visits (n = 183). Because regression-based mediation analyses test hypotheses about causal networks, the approach is only valid if the causal assumptions are appropriate.[@fiskeHandbookSocialPsychology2010] As such, we only considered mediation models in which the methylation probe and metabolite were temporally separated. For example, it is more reasonable to assume that a methylation site measured at PSV has a causal relationship with a metabolite measured at the SV visit (or vice versa) than to assume a causal relationship between two variables measured at the same time.

To reduce the number of methylation probe-metabolite pairs examined in the mediation analysis, we performed simple linear regression to find probes and metabolites that are correlated at a nominal p < 0.01 level. Next, we performed independent logistic regression on all significantly correlated pairs to determine those that were significantly associated with the IA outcome, again at a nominal 0.01 level. Pairs in which both metabolite and probe were correlated with one another, and both variables were associated with the outcome were selected for the mediation analysis. These p values were not adjusted for multiple comparisons because this was simply a candidate filtering step intended to save computing time later on. We selected 1490 pairs with methylation measured at PSV and metabolite measured at SV and 600 pairs with metabolite measured at PSV and methylation measured at SV for further investigation.

Model-based mediation analyses were performed using the regmedint package[@yoshidaRegmedintRegressionbasedCausal2020], an R implementation of Valeri and VanderWeele's SAS macros.[@valeriMediationAnalysisAllowing2013] We report the natural indirect effect (NIE), which can be interpreted as the effect of the exposure on the outcome that operates through changing the mediator.[@vanderweeleExplanationCausalInference2015] All regression models were adjusted for HLA-DR3/4 haplotype, age, time from PSV to SV, and sex. Confidence intervals for the NIE were calculated based on 10,000 bootstrap simulations using the percentile method.

# Results

# Discussion

- Limitations:
  - Non-fasting plasma samples for metabolomics, and these analyses did not account for dietary patterns.

\newpage

# References
