---
title: "MS Thesis Work"
author: "Tim Vigers"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_knit$set(root.dir = "C:/Users/tim/Documents/GitHub/MS-Thesis")
library(mediation)
library(parallel)
library(flextable)
library(tidyverse)
set.seed(1017)
```

# CIT Results

Of the metabolite - methylation pairs significant by CIT, the there was a relatively even split in terms of which was the mediator:

```{r}
# Import cit results
load("./data/networks/cits.Rdata")
# Annotate
gctof_anno = read.csv("./data/metabolomics/gctof.featureAnno.csv") %>% 
  select(BinBase.name,feature_name) %>% rename(name = BinBase.name)
hilic_anno = read.csv("./data/metabolomics/hilic.featureAnno.csv") %>%
  select(Metabolite.name,feature_name) %>% rename(name = Metabolite.name)
lipid_anno = read.csv("./data/metabolomics/lipid.featureAnno.csv") %>%
  select(Metabolite.name,feature_name) %>% rename(name = Metabolite.name)
vitd_anno = read.csv("./data/metabolomics/vitD.featureAnno.csv") %>%
  select(originalName,boxcoxDat_name) %>% 
  rename(name = originalName,feature_name = boxcoxDat_name)
oxylipin_anno = 
  read.csv("./data/metabolomics/oxylipin.featureAnno.csv") %>%
  select(full.name,cleanedDat_name) %>% 
  rename(name = full.name,feature_name = cleanedDat_name)
oxylipin_anno$feature_name = paste0("bc_",oxylipin_anno$feature_name)

anno = bind_rows(gctof_anno,hilic_anno,lipid_anno,vitd_anno,oxylipin_anno)

cits$metabolite = anno$name[match(cits$metab,anno$feature_name)]
# Repeats
repeats = cits[,c("methyl","metabolite")]
repeats = repeats[duplicated(repeats),]
# Convert arrow
cits$Mediator = factor(cits$direction,levels = c("<",">"),
                       labels = c("Methylation","Metabolite"))
# Print
table(cits$Mediator) %>% as.data.frame(.) %>% rename(Mediator = Var1) %>%
  flextable()
```

Of the above `r nrow(cits)` pairs, `r nrow(repeats)` were significant with both the metabolite and methylation probe as a mediator:

```{r}
repeats %>% rename(Methylation = methyl,Metabolite = metabolite) %>%
  flextable() %>% set_table_properties(.,layout = "autofit",width = 0.75)
```

# Less conservative mediation analysis

```{r}
load("./data/networks/all_data_methyl_scaled.Rdata")
load("./data/networks/pair_list.Rdata")
load("./data/probesFromPipeline.Rdata")
metab = cits$metab
# Mediation model lists
out_list = unique(paste0("factor(T1Dgroup)~",cits$methyl,"+",cits$metab))
# Cluster
cl = makeCluster(12)
clusterEvalQ(cl, library(mediation))
clusterExport(cl, c("out_list","all_data_methyl_scaled"))
cits_mediation = clusterApply(cl,out_list[1:12], function(t){
  split = strsplit(t,"\\~|\\+")
  y = glm(as.formula(t),data = all_data_methyl_scaled,family = "binomial")
  # methyl mediator
  m1_form = as.formula(paste0(split[[1]][2],"~",split[[1]][3]))
  m = lm(m1_form,data = all_data_methyl_scaled)
  med1 = mediate(m,y,mediator = split[[1]][2],treat = split[[1]][3])
  # metabolite mediator
  m2_form = as.formula(paste0(split[[1]][3],"~",split[[1]][2]))
  m = lm(m2_form,data = all_data_methyl_scaled)
  med2 = mediate(m,y,mediator = split[[1]][3],treat = split[[1]][2])
  # Results - what to report here?
})
stopCluster(cl)
save(cits_mediation,file = "./data/mediation/cits_mediation.Rdata")
```
