---
title: "Triad Selection - Unadjusted Models"
author: "Tim Vigers"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(tidyverse)
```

```{r import step 3,echo=FALSE}
# Import methylation association with T1D
methyl_step2 <- 
  read.csv("/Users/timvigers/GitHub/MS-Thesis/data/candidate_selection/step_2/methyl_adj.csv",
           stringsAsFactors = F)
methyl_step2 <- methyl_step2 %>% arrange(p.value,Value)
# Import metabolite associations with T1D
gctof_step3 <- 
  read.csv("/Users/timvigers/GitHub/MS-Thesis/data/candidate_selection/step_3/gctof_adj.csv",
           stringsAsFactors = F)
hilic_step3 <- 
  read.csv("/Users/timvigers/GitHub/MS-Thesis/data/candidate_selection/step_3/hilic_adj.csv",
           stringsAsFactors = F)
lipid_step3 <- 
  read.csv("/Users/timvigers/GitHub/MS-Thesis/data/candidate_selection/step_3/lipid_adj.csv",
           stringsAsFactors = F)
oxylipin_step3 <- 
  read.csv("/Users/timvigers/GitHub/MS-Thesis/data/candidate_selection/step_3/oxylipin_adj.csv",
           stringsAsFactors = F)
vitd_step3 <- 
  read.csv("/Users/timvigers/GitHub/MS-Thesis/data/candidate_selection/step_3/vitd_adj.csv",
           stringsAsFactors = F)
metab_step3 <- bind_rows(gctof_step3,hilic_step3,lipid_step3,oxylipin_step3,vitd_step3)
metab_step3 <- metab_step3 %>% arrange(p.value,Value)
```

# Step 1: Metabolite - Methylation

## GC-TOF Metabolites

```{r gctof unadj import,echo=FALSE}
gctof <- read.csv("/Users/timvigers/GitHub/MS-Thesis/data/candidate_selection/step_1/sv/gctof_SV_unadj_scaled.csv",
                  stringsAsFactors = F)
gctof <- gctof %>% arrange(p.value,Value)
methyl_pheno <- unique(methyl_step2$methyl[methyl_step2$p.value < 0.05])
metab_pheno <- unique(metab_step3$metab[metab_step3$p.value < 0.05])

pairs <- gctof[gctof$p.value < 0.001,]
pairs <- pairs[which(pairs$methyl %in% methyl_pheno | pairs$metab %in% metab_pheno),]
```

### Plots

```{r echo=FALSE}
volcano <- ggplot(gctof,aes(x = Value, y = -log(p.value,base = 10))) +
  geom_point() + 
  geom_point(data = pairs,color = "red") +
  theme_bw() + ylab("-log10 p-value") + xlab("Estimate") + ylim(0,15)
volcano
```

